require("core.options")
require("core.keymaps")

require("plugins.dash")
require("plugins.theme")
require("plugins.ui")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.format")
require("plugins.misc")
